language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

before_install:
 - sudo sh ./test/install-ffmpeg.sh

script:
 - python setup.py test

notifications:
  email:
    - tomaz+travis@tomaz.me
